# 锚点
#全部代理节点
all0: &all0 {type: select, include-all: true, filter: "^((?!(直连)).)*$"}

#全部节点
all1: &all1 {type: select, include-all: true}
# 机场订阅，名称不能重复
proxy-providers:
  Airport_01:
    type: http
    interval: 14400 #4小时一次
    health-check:
      enable: true
      url: http://cp.cloudflare.com/
      #url: http://www.msftconnecttest.com/connecttest.txt      
      #url: https://www.apple.com/library/test/success.html
      #url: https://www.qualcomm.cn/generate_204	
      #url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🟢 直连
    url: https://xxxx.com  
# 用于下载订阅时指定UA
global-ua:
    
# 全局配置
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
# interface-name: eth0  （路由器下根据情况指定出站接口）
#authentication:
  
#考虑ruleset的mrs比geodata查询效率要高，目前已替代geodata查询
#geoip 使用文件，mmdb 或者 dat，可选 true/false,true为 dat
geodata-mode: true
# GEO 文件加载模式（standard：标准加载器/memconservative：专为内存受限 (小内存) 设备优化的加载器 (默认值)）
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geosite: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# 控制面板
external-controller: 0.0.0.0:9090
secret: "123123"
external-ui: ui
external-ui-url: "https://ghfast.top/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

# 匹配进程 always/strict/off
find-process-mode: off
#global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# 策略组选择和fakeip缓存
profile:
  store-selected: true
  store-fake-ip: true
#hosts:
  #base-v4v6-cm-miguvideo.e.cdn.chinamobile.com: studentlive.migucloud.com

# 流量嗅探，默认情况下，sniffer 只对无域名的 IP 请求进行嗅探；force-domain 和 skip-domain针对特殊场景
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com" 
    
# 代理模式
tun:
  enable: true
  stack: mixed
  mtu: 9000
  # dns劫持
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  # 自动设置全局路由，可以自动将全局流量路由进入 tun 网卡
  auto-route: true
  auto-redirect: true
  # 自动选择流量出口接口
  auto-detect-interface: true
  
# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  #遵循分流规则,强烈不建议和 prefer-h3 一起使用
  respect-rules: true
  # 模式切换 redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # 模式切换 whitelist/blacklist 
  # 黑名单模式表示如果匹配成功则不返回 Fake-IP, 白名单模式时只有匹配成功才返回 Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    #加*就表示所有都在黑名单，也就是变成redir-host
    #- "*"
    - "+.lan"
    - "+.local"
    - RULE-SET:private_domain    
    - RULE-SET:cn_domain
    - RULE-SET:connectivity-check
    #DDNS
    - RULE-SET:mdirect  
    #GOOGLE TV 对时
    - aliyun.com  
  # 用于解析 DNS 服务器 的域名
  default-nameserver:    
    - 223.5.5.5
    - 119.29.29.29
  #指定域名查询的解析服务器，因为fallbake ip过滤域名缺省使用 nameserver 解析，所以对直连域名要指定国内DNS
  nameserver-policy:    
    "RULE-SET:cn_domain,private_domain,mdirect,connectivity-check":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query     
  #默认的域名解析服务器
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query    
  #代理节点域名解析服务器,开启遵循分流规则后，则必须加这一项
  proxy-server-nameserver:    
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query   
  #直连的域名解析服务器
  direct-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query     
proxies:
- name: "🟢 直连"
  type: direct
  udp: true

# 🎃 🌈  🔴🕺🍿💸🎮 🇭🇰 🇯🇵 🔮 🚁 自建 🧚 🎥 🎦 🎬 🍎 📺 🎶 👨‍💻 📢 Ⓜ️ ✈️ 🛩️ 📽️ 🏗️ 
# 策略组
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [🔮 节点均衡,🔯 节点故转,🇬 谷歌服务, 🚁 节点手动, ♻️ 节点自动,🌐 全部节点]}  
  - {name: 📹 YouTube, type: select, proxies: [🔮 节点均衡,🔯 节点故转,🇬 谷歌服务, 🚁 节点手动, ♻️ 节点自动]}
  - {name: 🇬 谷歌服务, <<: *all0}
  #- {name: 🤖 Ai_!cn, <<: *all0}
  - {name: 🕺 TvProxy, type: select, proxies: [🔮 节点均衡,🔯 节点故转,🇬 谷歌服务, 🚁 节点手动, ♻️ 节点自动]}
  - {name: 🪟 Microsoft, <<: *all1}
  - {name: 🍎 Apple, <<: *all1}
  - {name: ✈️ Speedtest, <<: *all0}
  - {name: 🌈 PrProxy, type: select, proxies: [🔮 节点均衡,🔯 节点故转,🇬 谷歌服务, 🚁 节点手动, ♻️ 节点自动]}    
  - {name: 🚁 节点手动, <<: *all0}
  
  - {name: 🎯 全球直连, <<: *all1}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🔮 节点均衡,🔯 节点故转,🇬 谷歌服务, 🚁 节点手动, ♻️ 节点自动, 🟢 直连]}  

  - {name: 🔯 节点故转, type: fallback,tolerance: 20, interval: 300, <<: *fallbk}  
  - {name: ♻️ 节点自动, type: url-test,tolerance: 20, interval: 300, <<: *fallbk}     
  - {name: 🔮 节点均衡, type: load-balance, interval: 300, strategy: round-robin, <<: *fallbk}  
  - {name: 🌐 全部节点, <<: *all1}
rules:
  # 若需禁用 QUIC 请取消注释 QUIC 两条规则
  # 防止 YouTube 等使用 QUIC 导致速度不佳, 禁用 443 端口 UDP 流量（不包括国内）
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_ip))),REJECT
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_domain))),REJECT  
  #禁用所有UDP流量
  - AND,((AND,(DST-PORT,443),(NETWORK,UDP))),REJECT  
  - DOMAIN-SUFFIX,googleapis.cn,🟢 直连
  - DOMAIN-SUFFIX,gstatic.com,🟢 直连
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🟢 直连
  - RULE-SET,mdirect,🟢 直连
  - RULE-SET,tvproxy,🕺 TvProxy
  
  - RULE-SET,private_domain,🟢 直连  
  - RULE-SET,connectivity-check,🟢 直连

  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,ai,📹 YouTube
  - RULE-SET,google_domain,📹 YouTube
  - DOMAIN,www.microsoft.com,🟢 直连  
  - RULE-SET,onedrive_domain,🪟 Microsoft 
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,microsoftcn_domain,🟢 直连
  - DOMAIN,www.apple.com,🟢 直连 
  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,applecn_domain,🟢 直连
  - RULE-SET,geolocation-!cn,🌈 PrProxy

  - RULE-SET,cn_domain,🎯 全球直连    
  #IP匹配  
  - RULE-SET,cloudflare_ip,🎯 全球直连,no-resolve
  - RULE-SET,google_ip,🇬 谷歌服务,no-resolve
  - RULE-SET,apple_ip,🍎 Apple,no-resolve
  - RULE-SET,twitter_ip,🌈 PrProxy,no-resolve
  - RULE-SET,telegram_ip,🌈 PrProxy,no-resolve
  - RULE-SET,private_ip,🎯 全球直连,no-resolve
  - RULE-SET,cloudflare_ip,🎯 全球直连,no-resolve
  - RULE-SET,cn_ip,🎯 全球直连
  
  - MATCH,🐟 漏网之鱼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qdomain: &qdomain {type: http, interval: 1800, behavior: domain, format: mrs}
  zdy: &zdy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }  
  mdirect: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/mdirect.mrs" }  
  tvproxy: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/tvproxy.mrs" }
  googlestore_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/googlestore.mrs" }
  connectivity-check: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/connectivity-check.mrs" }
  #秋风去广告
  ads_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"} 
  ai: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-chat-!cn.mrs" }  
  youtube_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  google_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  github_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  twitter_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  telegram_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  netflix_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  paypal_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  onedrive_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  microsoft_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  microsoftcn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs" }
  applecn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs" }
  apple_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  speedtest_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs" }
  tiktok_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }

  geolocation-!cn: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  cn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }  
  private_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs" }
  cn_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  cloudflare_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs" }
  twitter_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs" }
  telegram_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  apple_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs" }
  #facebook_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs" }
  netflix_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
